export const GET_USERS = "GET_USERS";
export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS_FULFILLED = "GET_USERS_FULFILLED";
export const GET_USERS_REJECTED = "GET_USERS_REJECTED";

export const ADD_USER = "ADD_USER";
export const ADD_USER_PENDING = "ADD_USER_PENDING";
export const ADD_USER_FULFILLED = "ADD_USER_FULFILLED";
export const ADD_USER_REJECTED = "ADD_USER_REJECTED";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_PENDING = "DELETE_USER_PENDING";
export const DELETE_USER_FULFILLED = "DELETE_USER_FULFILLED";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";

export const SELECT_USER = "SELECT_USER";
