export const GET_USERS = "GET_USERS";
export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS_FULFILLED = "GET_USERS_FULLFILLED";
export const GET_USERS_REJECTED = "GET_USERS_REJECTED";
